# File : .pep8speaks.yml

scanner:
    diff_only: True  # If True, errors caused by only the patch are shown

pycodestyle:
    max-line-length: 88  # Default is 79 in PEP8
    ignore:
      - E203 # whitespace before ':' has inconsistency between pycodestyle and black, so ignore
      - W503 # line break before binary operator has inconsistency between pycodestyle and black, so ignore
