name: black

on:
  pull_request:
    paths:
      - '**.py'

defaults:
  run:
    shell: bash

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Version
      run: |
        python --version
        black --version
    - name: Run black
      run: |
        black xbout
        black docs
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Apply black formatting"
